CREATE TABLE clientes(
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    rut VARCHAR2(9) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    telefono VARCHAR2(15) NOT NULL
);

CREATE TABLE comuna (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR2(25) NOT NULL
);

CREATE TABLE region (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR2(25) NOT NULL
);

CREATE TABLE tipo_cliente(
    id INT AUTO_INCREMENT PRIMARY KEY,
    tipo VARCHAR2(50) NOT NULL,
    descuento FLOAT(10) NOT NULL
);