server:
  port: 0

springdoc:
  api-docs:
    path: /salas/api-docs

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}

spring:
  application:
    name: salas
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    show-sql: true
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: root
    password: ''
    url: jdbc:mysql://${DATABASE_HOST:localhost}:3306/db_salas_dev?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update